#!/bin/bash
yum install -y httpd
echo "Hello from Instance A" > /var/www/html/index.html
systemctl start httpd
systemctl enable httpd


#!/bin/bash
yum install -y httpd
echo "Hello from Instance B" > /var/www/html/index.html
systemctl start httpd
systemctl enable httpd
